### ISSUE TITLE
zipreader in undistort_h36m.py

### ISSUE THREAD

**Issue by Vegetebird** [yihui-he/epipolar-transformers#11]
In undistort_h36m, after Process using the H36M-Toolbox, I don't get the images.zip@. So I can change the "zipreader.imread" to "cv2.imread"?

**Comment by yihui-he** [comment]
zip is not a must. you can set DATASETS.DATA_FORMAT = 'jpg' while training.
the undistort step can be omitted (unless u choose DATASETS.DATA_FORMAT = 'undistoredzip'), 
images can be undistorted on the fly. https://github.com/yihui-he/epipolar-transformers/blob/master/data/datasets/joints_dataset.py#L277
