### ISSUE TITLE
Can you report the inference speed of the algorithm (in terms of fps)?

### ISSUE THREAD

**Issue by gkagkos** [yihui-he/epipolar-transformers#13]
Thanks for the great work! In your results, you provide the number of parameters and MAC, however, it is unclear how this affects the inference speed (fps) of your algorithm. Can you report some numbers?  Also, have you compared it with other methods except for cross-view fusion?

**Comment by yihui-he** [comment]
this code is not well implemented for speed. The backbones of different views are duplicated instead of shared. Ideally, the speed should almost the same as single view model.
