### ISSUE TITLE
How to test on our own dataset ?

### ISSUE THREAD

**Issue by manansaxena** [yihui-he/epipolar-transformers#16]
Thanks a lot for the great work and open-sourcing the intense code repo. Could you please give a few pointers on how to test a pretrained model on our own custom dataset?

**Comment by yimengli46** [comment]
Have you figured out how to do that?
I tried some images but the results are really bad.

**Comment by manansaxena** [comment]
Sorry, didn't continue with this approach.

**Comment by zxk19981227** [comment]
Same problem. Also i met great problems on the two pretrained model but the `pose_resnet_4.5_pixels_human36m.pth` predicts  33 joints  while  all the configs have up to 20 joints？
