### ISSUE TITLE
Train on RHD dataset error

### ISSUE THREAD

**Issue by sulei1998** [yihui-he/epipolar-transformers#17]
Thanks for your great work! But when i tried train on RHD dataset, I met the error like this:
![image](https://user-images.githubusercontent.com/56378342/110203183-96d34b00-7ea7-11eb-97cb-3bdb396a5a06.png)

I use `python main.py --cfg configs/lifting/lifting_direct.yaml` to run the main.py.
Could you give me some advice?

**Comment by yihui-he** [comment]
its fixed now. PCK shouldn't be tested during testing for RHD

https://github.com/yihui-he/epipolar-transformers/blob/4da5cbca762aef6a89d37f889789f772b87d2688/configs/lifting/lifting_direct.yaml#L13-L14
