### ISSUE TITLE
Question about number of views

### ISSUE THREAD

**Issue by HowieMa** [yihui-he/epipolar-transformers#21]
Hi, thank you for sharing such an amazing work. I have some questions about the number of views, and I sincerely hope you could help me with them.  
1 How can I adjust your code to obtain the results in Figure 7? It seems that you only use one source view in both training and testing, as the [Top K](https://github.com/yihui-he/epipolar-transformers/blob/master/configs/epipolar/keypoint_h36m_resnet152_384_pretrained_8gpu.yaml#L30) is always 1.  Thus I am curious on how to obtain the results with only 2 views. 

2 Based on Table 6, Resnet50 on 256 * 256 + triangulate already achieves 48.7 mm. However, based on Figure 7, the Crossview + triangulate[28] achieves more than 70 mm in two views, which is even worse than the baseline without any fusion. This is a little strange, could you please share some details about this? 

Look forward to your reply, thanks in advance!

**Comment by yihui-he** [comment]
1. similar with Figure 5, random pair of views is used when there're more than 2 views. 
2. i don't see 70mm u referred. But some details are more refined than [28] which results in a stronger baseline.

**Comment by HowieMa** [comment]
Thank you so much for your quick reply. 
The 70 mm is the result of 2 views for crossview+triangulation in Figure 7, which performs even worse than the baseline ResNet50 without any fusion (48.7 mm). 
![image](https://user-images.githubusercontent.com/25797674/118869303-0eefc100-b89a-11eb-8645-305f0da31da0.png)

**Comment by yihui-he** [comment]
I got that result by reducing views in their code. The difference came from some implementation details.

**Comment by HowieMa** [comment]
> I got that result by reducing views in their code. The difference came from some implementation details.

Thanks. That's very helpful!
