### ISSUE TITLE
Question about the extrinsic matrix of human3.6M

### ISSUE THREAD

**Issue by sulei1998** [yihui-he/epipolar-transformers#30]
Thanks for your code! I just came into contact with the dataset of human 3.6. I noticed that the `R` and `t` of camera parameters in the dataset will change in different actors. At the same time, I also calculated the external parameters between different cameras and found that they will change between different actors. Is this because the positions of the four cameras did change during their data collection, or because I misunderstood？

**Comment by Alex-JYJ** [comment]
Yes, the external parameters of 4 cameras changed between different actors

**Comment by sulei1998** [comment]
Thanks for your reply! If anyone is interested in multi-view 3D human pose estimation, you can add my WeChat to discuss and exchange.
![1DD1F67F8140D79A49FCD2999D1DCF07](https://user-images.githubusercontent.com/56378342/143973128-8c20df5b-c34c-4eb2-a3aa-913378be31bc.png)
