### ISSUE TITLE
Questions about the number of view

### ISSUE THREAD

**Issue by sulei1998** [yihui-he/epipolar-transformers#31]
Hi, thanks for your work! When I run your code from four views, the results look good. But I when run the code with two views it seems bad! I was confused. Could you give me some advice?

**Test on 4 Views**
![image](https://user-images.githubusercontent.com/56378342/143799774-94f48ba3-ad76-4eef-9662-9ca997ce0084.png)

**Test on 2 Views**
![image](https://user-images.githubusercontent.com/56378342/143799831-be58407f-9d4d-4f01-999b-b03daa038f02.png)

**Comment by sulei1998** [comment]
By the way, i use the 'keypoint_h36m_zresidual_fixed.yaml' and change the inputs.

**Comment by yihui-he** [comment]
the four view version simply aggregate two view results
