### ISSUE TITLE
请问EPIPOLAR.PRIOR这个参数是代表什么含义？

### ISSUE THREAD

**Issue by peiyubin** [yihui-he/epipolar-transformers#33]
感谢您的开源分享，我在配置参数当中看到了EPIPOLAR.PRIOR这个布尔值，我不太明白它的作用是什么？能否请您指点一二，谢谢您的指导

**Comment by yihui-he** [comment]
https://github.com/yihui-he/epipolar-transformers/blob/f443933a18d38d4b61f54e36fec4c712edbe62cc/core/config.py#L103

it means the attention is fixed
