### ISSUE TITLE
Question on skipping those points with  epipolar lines which have no intersection with the source view

### ISSUE THREAD

**Issue by huangchaoxing** [yihui-he/epipolar-transformers#8]
Hi 

I got a question on skipping those "bad" points. 

When you skip those points, how can you still ensure the feature map which is computed by eq (2) has the same pixel number as the input ?

Thank you

**Comment by yihui-he** [comment]
If an epipolar line has no intersection with the source view, eq (2) will be skipped for it, aka the weighted sum will be 0.
