### ISSUE TITLE
memory consumption 

### ISSUE THREAD

**Issue by paulchhuang** [yihui-he/epipolar-transformers#9]
Hi, 

I'm reproducing training H36m with config keypoint_h36m_zresidual_fixed.yaml. The program kept eating up RAM during the progress. I use pytorch 1.3.0 following the setup instructions. Did you observe anything alike? Any pointer or thought would be more than welcome. Thanks in advance!

**Comment by yihui-he** [comment]
how much RAM do u have? there was indeed memory leak issue. > 256GB ram should work

**Comment by paulchhuang** [comment]
Thanks for the prompt reply! yihui-he. I increased the max allowed RAM. It runs but after a while got another error:

```
python: /opt/conda/conda-bld/magma-cuda101_1564975897942/work/interface_cuda/interface.cpp:810: void magma_queue_create_internal(magma_device_t, magma_queue**, const char*, const char*, int): Assertion `queue->dCarray__ != __null' failed.
```

Having checked on the Internet, it seems to be related to this issue: https://github.com/pytorch/pytorch/issues/26120

Have u encountered similar problems in your experiment? If not, may I know which pytorch version you use?

**Comment by yihui-he** [comment]
No. 
I used 1.3
